[[current_thing]]

whatnow = [
    { something = "Building JobAppTrackr and rupantar"},
    { something = "Learning C# and Golang"} ,
    { something = "Finding ways to improve projects that I have worked on in the past with my current knowledge(never settle!)" },
    { something = "Self-hosting apps & services, and just overall experimenting, on my home server"},
    { something = "Practicing mindfulness and gratitude" },
    { something = "Reading The Count of Monte Cristo (finishing novel backlog!)" },
]

[[timing]]

date = "December 5, 2023"
