[[project]]

name = "JobAppTrackr"

desc = "Web app for tracking and managing job applications effectively"

skills = [
    {learnt = "ASP.NET Core"},
    {learnt = "React"},
    {learnt = "MongoDB"}
]

links = [

        {name = "GitHub", url = "https://github.com/Bhodrolok/JobAppTrackr"}

]


#