[[current_thing]]

whatnow = [
    { something = "Working on building JobAppTrackr and rupantar"},
    { something = "Learning new concepts and tech stacks"} ,
    { something = "Figuring out ways to improve projects I worked on in the past" },
    { something = "Experimenting on my home server!"},
    { something = "Practicing mindfulness and gratitude" },
    { something = "Trying to incorporate aspects of modern Agile and DevOps practices into day-to-day IRL stuff outside software development and project management" },
]

[[timing]]

date = "June 23, 2023"
